### ISSUE TITLE
docker-compose fail in local development

### ISSUE THREAD

**Issue by parweb** [quirrel-dev/demo.quirrel.dev#1]
When I try to setup quirrel in local throught docker-compose

```yml
version: '3.7'

services:
  quirrel:
    image: docker.pkg.github.com/quirrel-dev/quirrel/quirrel
    environment:
      REDIS_URL: redis://redis
    ports:
      - '9181:9181'

  redis:
    image: redis
```

```bash
docker-compose up
```

I get an error, asking me a password

```bash
Pulling quirrel (docker.pkg.github.com/quirrel-dev/quirrel/quirrel:)...
ERROR: Get https://docker.pkg.github.com/v2/quirrel-dev/quirrel/quirrel/manifests/latest: no basic auth credentials
```
